#!/usr/bin/env bash
# audit-event-participation.sh
# Scans service directories for event publishing, consumption, idempotency, and DLQ.
# Output: markdown table for comparison with docs/10-appendix/checklists/workflow/event-processing-service-audit.md
# Run from repo root: ./docs/scripts/audit-event-participation.sh

set -e
REPO_ROOT="${REPO_ROOT:-$(cd "$(dirname "$0")/../.." && pwd)}"
cd "$REPO_ROOT"

SERVICES="order checkout return payment catalog search warehouse pricing promotion fulfillment shipping location customer auth user review analytics notification loyalty-rewards gateway common-operations"

has_any() {
  local dir="$1"
  shift
  for pattern in "$@"; do
    if find "$dir" -type f \( -name "*.go" -o -name "*.yaml" -o -name "*.yml" \) 2>/dev/null | grep -q "$pattern"; then
      return 0
    fi
  done
  return 1
}

echo "| Service | Publisher | Consumer | Idempotency | DLQ |"
echo "|---------|-----------|----------|-------------|-----|"

for svc in $SERVICES; do
  dir="$svc"
  if [ ! -d "$dir" ]; then
    echo "| $svc | — | — | — | — | (dir not found)"
    continue
  fi

  pub="N"
  if [ "$svc" = "gateway" ]; then
    pub="—"
  else
    ( has_any "$dir" "outbox" "events/publisher" "event/publisher" "EventHelper" "PublishEvent" "PublishCreated" ) && pub="Y"
  fi

  con="N"
  if [ "$svc" = "gateway" ]; then
    con="—"
  else
    ( has_any "$dir" "eventbus/" "observer/" "dapr_subscription" "subscription.yaml" "AddTopicEventHandler" ) && con="Y"
  fi

  idem="N"
  if [ "$pub" = "—" ] && [ "$con" = "—" ]; then
    idem="—"
  elif [ "$con" = "Y" ]; then
    ( has_any "$dir" "event_idempotency" "IsProcessed" "MarkProcessed" ) && idem="Y"
  else
    idem="—"
  fi

  dlq="N"
  if [ "$con" = "—" ] || [ "$con" = "N" ]; then
    dlq="—"
  else
    ( has_any "$dir" "deadLetterTopic" "dlq" "DeadLetter" ) && dlq="Y"
  fi

  echo "| $svc | $pub | $con | $idem | $dlq |"
done

echo ""
echo "Generated by $0 at $(date -u +%Y-%m-%dT%H:%M:%SZ). Compare with docs/10-appendix/checklists/workflow/event-processing-service-audit.md"
